recommend_task :
  description: >
    My information is described in the knowledge file. Please refer to it.
    Please recommend keywords that provide insight into business sustainability and expansion strategies targeting the prospective client, {company}.
    Finally, translate the output into Korean and emphasize the important parts by adding asterisks (*).
  expected_output: >
    A list of strategic keywords to help successfully approach and sell to {company}.
  agent: recommender

investigate_task :
    description: >
      My information is described in the knowledge file. Please refer to it.
      Research the current trends for the keywords suggested by the Keyword Recommender. Use Google Trends and other websites to gather trend data and summarize insights.
      Finally, translate the output into Korean and emphasize the important parts by adding asterisks (*).
    expected_output: >
      A summarized trend report for each keyword, including interest levels, regional patterns, and recent mentions or news.
    agent: trend_investigator

propose_strategy_task :
    description: >
      Our company's service information is described in the knowledge file. Please refer to it.
      Based on information about the sales target, {company}, and the keyword trend report, please propose innovative and practical strategies that can support the growth and differentiation of my business.      
      Finally, translate the output into Korean and emphasize the important parts by adding asterisks (*).
    expected_output: >
      Strategic recommendations for my business targeting {company}, grounded in keyword insights and trend data.
    agent: strategy_advisor

#translate_task:
#    description: >
#      Translate the each strategy_advisor's English output and consultant’s English output into clear and natural Korean.
#      Finally Change it to a markdown format.
#    expected_output: >
#      A Korean translation of the consultant’s recommendations that preserves original meaning
#      and is easy for Korean sales reps to understand.
#    agent: translator
