recommend_task :
  description: >
    Based on the {company}, analyze its business domain and recommend keywords that offer insight for sustaining and expanding its business.
    Finally, translate the output into Korean.
  expected_output: >
    A list of strategic keywords relevant to the {company}'s current and future business directions.
  agent: recommender

investigate_task :
    description: >
      Research the current trends for the keywords suggested by the Keyword Recommender. Use Google Trends and other websites to gather trend data and summarize insights.
      Finally, translate the output into Korean.
    expected_output: >
      A summarized trend report for each keyword, including interest levels, regional patterns, and recent mentions or news.
    agent: trend_investigator

propose_strategy_task :
    description: >
      Based on the {company} profile and the keyword trend report, propose innovative and practical strategies that could support business growth and differentiation.
      Finally, translate the output into Korean.
    expected_output: >
      Strategic recommendations tailored to the {company}'s domain, supported by keyword insights and trend data.
    agent: strategy_advisor

#translate_task:
#    description: >
#      Translate the each strategy_advisor's English output and consultant’s English output into clear and natural Korean.
#      Finally Change it to a markdown format.
#    expected_output: >
#      A Korean translation of the consultant’s recommendations that preserves original meaning
#      and is easy for Korean sales reps to understand.
#    agent: translator
